-- MySQL Script generated by MySQL Workbench
-- Fri Jan 27 16:18:30 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema u841648456_dbfcp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `u841648456_dbfcp` ;

-- -----------------------------------------------------
-- Schema u841648456_dbfcp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `u841648456_dbfcp` DEFAULT CHARACTER SET utf8 ;
USE `u841648456_dbfcp` ;

-- -----------------------------------------------------
-- Table `u841648456_dbfcp`.`setor_fundacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u841648456_dbfcp`.`setor_fundacao` ;

CREATE TABLE IF NOT EXISTS `u841648456_dbfcp`.`setor_fundacao` (
  `id_setor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_setor`))
;


-- -----------------------------------------------------
-- Table `u841648456_dbfcp`.`usuario_fundacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u841648456_dbfcp`.`usuario_fundacao` ;

CREATE TABLE IF NOT EXISTS `u841648456_dbfcp`.`usuario_fundacao` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `tipo_usuario` INT NOT NULL COMMENT '1 = Moderador;\n2 = Gerente;',
  `id_gerente` INT NULL COMMENT 'Caso o usuário seja moderador, ele terá que \"depender\" de um gerente, portanto será relacionado o moderador com o id_gerente.',
  PRIMARY KEY (`id_usuario`))
;


-- -----------------------------------------------------
-- Table `u841648456_dbfcp`.`setor_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u841648456_dbfcp`.`setor_usuario` ;

CREATE TABLE IF NOT EXISTS `u841648456_dbfcp`.`setor_usuario` (
  `id_setor` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_setor`, `id_usuario`),
  INDEX `fk_usuario_fundacao_has_setor_fundacao_setor_fundacao1_idx` (`id_setor` ASC),
  INDEX `fk_usuario_fundacao_has_setor_fundacao_usuario_fundacao1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_usuario_fundacao_has_setor_fundacao_usuario_fundacao1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `u841648456_dbfcp`.`usuario_fundacao` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_fundacao_has_setor_fundacao_setor_fundacao1`
    FOREIGN KEY (`id_setor`)
    REFERENCES `u841648456_dbfcp`.`setor_fundacao` (`id_setor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `u841648456_dbfcp`.`contato_setor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u841648456_dbfcp`.`contato_setor` ;

CREATE TABLE IF NOT EXISTS `u841648456_dbfcp`.`contato_setor` (
  `id_contato` INT NOT NULL AUTO_INCREMENT,
  `id_setor` INT NOT NULL,
  `area_atuacao` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_contato`, `id_setor`),
  INDEX `fk_contato_setor_setor_fundacao1_idx` (`id_setor` ASC),
  CONSTRAINT `fk_contato_setor_setor_fundacao1`
    FOREIGN KEY (`id_setor`)
    REFERENCES `u841648456_dbfcp`.`setor_fundacao` (`id_setor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `u841648456_dbfcp`.`evento_cinema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u841648456_dbfcp`.`evento_cinema` ;

CREATE TABLE IF NOT EXISTS `u841648456_dbfcp`.`evento_cinema` (
  `id_evento` INT NOT NULL AUTO_INCREMENT,
  `id_setor` INT NOT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `programacao_regular` VARCHAR(80) NOT NULL,
  `projetos` VARCHAR(80) NULL,
  `horario` DATETIME NOT NULL,
  `preco` FLOAT NOT NULL,
  PRIMARY KEY (`id_evento`, `id_setor`),
  INDEX `fk_CineLibero_setor_fundacao1_idx` (`id_setor` ASC),
  CONSTRAINT `fk_CineLibero_setor_fundacao1`
    FOREIGN KEY (`id_setor`)
    REFERENCES `u841648456_dbfcp`.`setor_fundacao` (`id_setor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `u841648456_dbfcp`.`evento_biblioteca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u841648456_dbfcp`.`evento_biblioteca` ;

CREATE TABLE IF NOT EXISTS `u841648456_dbfcp`.`evento_biblioteca` (
  `id_evento` INT NOT NULL AUTO_INCREMENT,
  `id_setor` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `horario` DATETIME NOT NULL,
  `preco` FLOAT NULL,
  PRIMARY KEY (`id_evento`, `id_setor`),
  INDEX `fk_Biblioteca_setor_fundacao1_idx` (`id_setor` ASC),
  CONSTRAINT `fk_Biblioteca_setor_fundacao1`
    FOREIGN KEY (`id_setor`)
    REFERENCES `u841648456_dbfcp`.`setor_fundacao` (`id_setor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `u841648456_dbfcp`.`evento_centro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u841648456_dbfcp`.`evento_centro` ;

CREATE TABLE IF NOT EXISTS `u841648456_dbfcp`.`evento_centro` (
  `id_evento` INT NOT NULL AUTO_INCREMENT,
  `id_setor` INT NOT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `local` VARCHAR(80) NOT NULL,
  `horario` DATETIME NOT NULL,
  `preco` FLOAT NOT NULL,
  PRIMARY KEY (`id_evento`, `id_setor`),
  INDEX `fk_CIN_setor_fundacao1_idx` (`id_setor` ASC),
  CONSTRAINT `fk_CIN_setor_fundacao1`
    FOREIGN KEY (`id_setor`)
    REFERENCES `u841648456_dbfcp`.`setor_fundacao` (`id_setor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `u841648456_dbfcp`.`evento_teatro_margarida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u841648456_dbfcp`.`evento_teatro_margarida` ;

CREATE TABLE IF NOT EXISTS `u841648456_dbfcp`.`evento_teatro_margarida` (
  `id_evento` INT NOT NULL AUTO_INCREMENT,
  `id_setor` INT NOT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `horario` DATETIME NOT NULL,
  `preco` FLOAT NOT NULL,
  PRIMARY KEY (`id_evento`, `id_setor`),
  INDEX `fk_Teatro Margarida_setor_fundacao1_idx` (`id_setor` ASC),
  CONSTRAINT `fk_Teatro Margarida_setor_fundacao1`
    FOREIGN KEY (`id_setor`)
    REFERENCES `u841648456_dbfcp`.`setor_fundacao` (`id_setor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `u841648456_dbfcp`.`evento_teatro_waldemar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u841648456_dbfcp`.`evento_teatro_waldemar` ;

CREATE TABLE IF NOT EXISTS `u841648456_dbfcp`.`evento_teatro_waldemar` (
  `id_evento` INT NOT NULL AUTO_INCREMENT,
  `id_setor` INT NOT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `decricao` VARCHAR(255) NOT NULL,
  `horario` DATETIME NOT NULL,
  `preco` FLOAT NOT NULL,
  PRIMARY KEY (`id_evento`, `id_setor`),
  INDEX `fk_Teatro Waldemar_setor_fundacao1_idx` (`id_setor` ASC),
  CONSTRAINT `fk_Teatro Waldemar_setor_fundacao1`
    FOREIGN KEY (`id_setor`)
    REFERENCES `u841648456_dbfcp`.`setor_fundacao` (`id_setor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `u841648456_dbfcp`.`evento_casa_linguagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u841648456_dbfcp`.`evento_casa_linguagem` ;

CREATE TABLE IF NOT EXISTS `u841648456_dbfcp`.`evento_casa_linguagem` (
  `id_evento` INT NOT NULL AUTO_INCREMENT,
  `id_setor` INT NOT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `horario` DATETIME NOT NULL,
  `preco` FLOAT NOT NULL,
  PRIMARY KEY (`id_evento`, `id_setor`),
  INDEX `fk_Casa da Linguagem_setor_fundacao1_idx` (`id_setor` ASC),
  CONSTRAINT `fk_Casa da Linguagem_setor_fundacao1`
    FOREIGN KEY (`id_setor`)
    REFERENCES `u841648456_dbfcp`.`setor_fundacao` (`id_setor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `u841648456_dbfcp`.`evento_curro_velho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u841648456_dbfcp`.`evento_curro_velho` ;

CREATE TABLE IF NOT EXISTS `u841648456_dbfcp`.`evento_curro_velho` (
  `id_evento` INT NOT NULL AUTO_INCREMENT,
  `id_setor` INT NOT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `oficina` VARCHAR(80) NOT NULL,
  `horario` DATETIME NOT NULL,
  `preco` FLOAT NOT NULL,
  PRIMARY KEY (`id_evento`, `id_setor`),
  INDEX `fk_Curro Velho_setor_fundacao1_idx` (`id_setor` ASC),
  CONSTRAINT `fk_Curro Velho_setor_fundacao1`
    FOREIGN KEY (`id_setor`)
    REFERENCES `u841648456_dbfcp`.`setor_fundacao` (`id_setor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `u841648456_dbfcp`.`evento_casa_artes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u841648456_dbfcp`.`evento_casa_artes` ;

CREATE TABLE IF NOT EXISTS `u841648456_dbfcp`.`evento_casa_artes` (
  `id_evento` INT NOT NULL AUTO_INCREMENT,
  `id_setor` INT NOT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `oficina` VARCHAR(80) NOT NULL,
  `horario` DATETIME NOT NULL,
  `preco` FLOAT NULL,
  PRIMARY KEY (`id_evento`, `id_setor`),
  INDEX `fk_Casa das Artes_setor_fundacao1_idx` (`id_setor` ASC),
  CONSTRAINT `fk_Casa das Artes_setor_fundacao1`
    FOREIGN KEY (`id_setor`)
    REFERENCES `u841648456_dbfcp`.`setor_fundacao` (`id_setor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `u841648456_dbfcp`.`evento_galeria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u841648456_dbfcp`.`evento_galeria` ;

CREATE TABLE IF NOT EXISTS `u841648456_dbfcp`.`evento_galeria` (
  `id_evento` INT NOT NULL AUTO_INCREMENT,
  `id_setor` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `horario` DATETIME NOT NULL,
  `preco` FLOAT NOT NULL,
  PRIMARY KEY (`id_evento`, `id_setor`),
  INDEX `fk_Galeria_setor_fundacao1_idx` (`id_setor` ASC),
  CONSTRAINT `fk_Galeria_setor_fundacao1`
    FOREIGN KEY (`id_setor`)
    REFERENCES `u841648456_dbfcp`.`setor_fundacao` (`id_setor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;


-- -----------------------------------------------------
-- Table `u841648456_dbfcp`.`super_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u841648456_dbfcp`.`super_user` ;

CREATE TABLE IF NOT EXISTS `u841648456_dbfcp`.`super_user` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `tipo_usuario` INT NOT NULL,
  PRIMARY KEY (`id_super_user`))
;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- INSERÇÃO SUPER_USER
INSERT INTO `db_fcp`.`super_user` (`nome_usuario`, `login`, `senha`, `tipo_usuario`) VALUES ("ADMIN", "fcp_admin", "@fcpadmin123", 0);

-- INSERÇÃO USER
INSERT INTO `db_fcp`.`usuario_fundacao` (nome_usuario, login, senha, tipo_usuario, id_gerente) VALUES ("Gerente Cine", "gerente_cine", "gerente_cine123", 2, 0);
INSERT INTO `db_fcp`.`usuario_fundacao` (nome_usuario, login, senha, tipo_usuario, id_gerente) VALUES ("Gerente Artes", "gerente_artes", "gerente_artes123", 2, 0);
INSERT INTO `db_fcp`.`usuario_fundacao` (nome_usuario, login, senha, tipo_usuario, id_gerente) VALUES ("Gerente Linguagem", "gerente_linguagem", "gerente_clinguagem123",2, 0);
INSERT INTO `db_fcp`.`usuario_fundacao` (nome_usuario, login, senha, tipo_usuario, id_gerente) VALUES ("Moderador Cine", "user_cine", "user_cine123", 1, 1);
INSERT INTO `db_fcp`.`usuario_fundacao` (nome_usuario, login, senha, tipo_usuario, id_gerente) VALUES ("Moderador Artes", "user_artes", "user_artes123", 1, 2);
INSERT INTO `db_fcp`.`usuario_fundacao` (nome_usuario, login, senha, tipo_usuario, id_gerente) VALUES ("Moderador Linguagem", "user_linguagem", "user_linguagem123", 1, 3);

-- INSERÇÃO SETOR_FUNDACAO
INSERT INTO `u841648456_dbfcp`.`setor_fundacao` (`nome`) VALUES ("BIBLIOTECA ARTHUR VIANA");
INSERT INTO `u841648456_dbfcp`.`setor_fundacao` (`nome`) VALUES ("CASA DAS ARTES");
INSERT INTO `u841648456_dbfcp`.`setor_fundacao` (`nome`) VALUES ("CASA DA LINGUAGEM");
INSERT INTO `u841648456_dbfcp`.`setor_fundacao` (`nome`) VALUES ("CENTRO DE EVENTOS ISMAEL NERY");
INSERT INTO `u841648456_dbfcp`.`setor_fundacao` (`nome`) VALUES ("CINE-TEATRO LIBERO LUXARDO");
INSERT INTO `u841648456_dbfcp`.`setor_fundacao` (`nome`) VALUES ("NÚCLEO DE OFICINAS CURRO VELHO");
INSERT INTO `u841648456_dbfcp`.`setor_fundacao` (`nome`) VALUES ("TEATRO MARGARIDA SCHIVASAPPA");
INSERT INTO `u841648456_dbfcp`.`setor_fundacao` (`nome`) VALUES ("TEATRO EXPERIMENTAL WALDEMAR HENRIQUE");
